export const FETCH_COLLECTIONS = 'FETCH_COLLECTIONS';
export const COLLECTIONS_LOADING = 'COLLECTIONS_LOADING';
export const COLLECTIONS_LOADED = 'COLLECTIONS_LOADED';

export const SAVE_ARTICLE = 'SAVE_ARTICLE';
export const UNSAVE_ARTICLE = 'UNSAVE_ARTICLE';
